"""Produto: campo subcategoria + indice

Revision ID: 92f69b790884
Revises: 975ad6652657
Create Date: 2026-04-18 13:57:15.345696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92f69b790884'
down_revision = '975ad6652657'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produtos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subcategoria', sa.String(length=50), nullable=True))
        batch_op.create_index(batch_op.f('ix_produtos_categoria'), ['categoria'], unique=False)
        batch_op.create_index(batch_op.f('ix_produtos_subcategoria'), ['subcategoria'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produtos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_produtos_subcategoria'))
        batch_op.drop_index(batch_op.f('ix_produtos_categoria'))
        batch_op.drop_column('subcategoria')

    # ### end Alembic commands ###
