"""Fornecedor: dados bancarios (pix, banco, agencia, conta)

Revision ID: 975ad6652657
Revises: 4f92e19ce81a
Create Date: 2026-04-17 09:33:34.856781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '975ad6652657'
down_revision = '4f92e19ce81a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fornecedores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('chave_pix', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('banco', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('agencia', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('conta', sa.String(length=30), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fornecedores', schema=None) as batch_op:
        batch_op.drop_column('conta')
        batch_op.drop_column('agencia')
        batch_op.drop_column('banco')
        batch_op.drop_column('chave_pix')

    # ### end Alembic commands ###
