"""participacao_rodada_moderacao_pedido

Revision ID: b57d38351ad7
Revises: c40a4549b4d8
Create Date: 2026-04-18 15:23:03.617307

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b57d38351ad7'
down_revision = 'c40a4549b4d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('participacoes_rodada', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pedido_enviado_em', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('pedido_aprovado_em', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('pedido_aprovado_por_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('pedido_devolvido_em', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('pedido_motivo_devolucao', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('pedido_reprovado_em', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key('fk_participacao_pedido_aprovado_por', 'usuarios', ['pedido_aprovado_por_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('participacoes_rodada', schema=None) as batch_op:
        batch_op.drop_constraint('fk_participacao_pedido_aprovado_por', type_='foreignkey')
        batch_op.drop_column('pedido_reprovado_em')
        batch_op.drop_column('pedido_motivo_devolucao')
        batch_op.drop_column('pedido_devolvido_em')
        batch_op.drop_column('pedido_aprovado_por_id')
        batch_op.drop_column('pedido_aprovado_em')
        batch_op.drop_column('pedido_enviado_em')

    # ### end Alembic commands ###
