"""RodadaProduto: catalogo da rodada + preco de partida + aprovacao

Revision ID: c40a4549b4d8
Revises: 92f69b790884
Create Date: 2026-04-18 14:06:17.563405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c40a4549b4d8'
down_revision = '92f69b790884'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rodada_produtos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rodada_id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('preco_partida', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('adicionado_por_fornecedor_id', sa.Integer(), nullable=True),
    sa.Column('aprovado', sa.Boolean(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['adicionado_por_fornecedor_id'], ['fornecedores.id'], ),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], ),
    sa.ForeignKeyConstraint(['rodada_id'], ['rodadas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rodada_id', 'produto_id', name='uq_rodada_produto')
    )
    with op.batch_alter_table('rodada_produtos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rodada_produtos_produto_id'), ['produto_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rodada_produtos_rodada_id'), ['rodada_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rodada_produtos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rodada_produtos_rodada_id'))
        batch_op.drop_index(batch_op.f('ix_rodada_produtos_produto_id'))

    op.drop_table('rodada_produtos')
    # ### end Alembic commands ###
